package bola8.gui;

import bola8.entes.Mundo;
import bola8.fases.Fase;
import bola8.fases.Fase1;
import bola8.fases.Fase2;
import bola8.fases.Fase3;
import bola8.fases.Fase4;
import java.awt.BorderLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;
import javax.swing.UIManager;

/**
 * Marco (ventana) donde se muestra el juego.
 *
 * @author Jorge Berjano
 */
public class Marco extends javax.swing.JFrame {

    private Mundo mundo;
    private Lienzo lienzo;
    private Fase fase;
    private ActionListener tarea;
    private Timer timer;

    /**
     * Creates new form Marco
     */
    public Marco() {
        initComponents();

        mundo = new Mundo();
        lienzo = new Lienzo(mundo);

        panelJuego.add(lienzo, BorderLayout.CENTER);
        pack();

        iniciar();

        int latencia = 20; // milisegundos
        tarea = new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent evt) {
                mundo.mover();
                lienzo.validate();
                lienzo.repaint();
            }
        };
        timer = new Timer(latencia, tarea);
    }

    private void iniciar() {
//        ticInicio = System.currentTimeMillis();
        mundo.limpiar();

        int i = comboPrueba.getSelectedIndex();
        switch (i) {
            case 0:
                fase = new Fase3();
                break;
            case 1:
                fase = new Fase2();
                break;
            case 2:
                fase = new Fase1();
                break;
            case 3:
                fase = new Fase4();
                break;
        }
        fase.inicializar(lienzo);
        lienzo.validate();
        lienzo.repaint();
    }

    private void actualizarEstado() {
        if (botonAuto.isSelected()) {
            timer.start();
        } else {
            timer.stop();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelConsola = new javax.swing.JPanel();
        comboPrueba = new javax.swing.JComboBox();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 6), new java.awt.Dimension(0, 6), new java.awt.Dimension(32767, 6));
        botonAuto = new javax.swing.JToggleButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 6), new java.awt.Dimension(0, 6), new java.awt.Dimension(32767, 6));
        botonPaso = new javax.swing.JButton();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 6), new java.awt.Dimension(0, 6), new java.awt.Dimension(32767, 6));
        botonIniciar = new javax.swing.JButton();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 6), new java.awt.Dimension(0, 6), new java.awt.Dimension(32767, 6));
        etiquetaTiempo = new javax.swing.JLabel();
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 6), new java.awt.Dimension(0, 6), new java.awt.Dimension(32767, 6));
        panelBorde = new javax.swing.JPanel();
        panelJuego = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelConsola.setBorder(javax.swing.BorderFactory.createEmptyBorder(6, 6, 6, 6));
        panelConsola.setAlignmentX(0.0F);
        panelConsola.setAlignmentY(0.0F);
        panelConsola.setLayout(new javax.swing.BoxLayout(panelConsola, javax.swing.BoxLayout.PAGE_AXIS));

        comboPrueba.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Prueba 1", "Prueba 2", "Prueba 3", "Prueba 4", "Prueba 5", "Prueba 6" }));
        comboPrueba.setMaximumSize(new java.awt.Dimension(32767, 22));
        comboPrueba.setName(""); // NOI18N
        comboPrueba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboPruebaActionPerformed(evt);
            }
        });
        panelConsola.add(comboPrueba);
        panelConsola.add(filler2);

        botonAuto.setText("auto");
        botonAuto.setAlignmentX(0.5F);
        botonAuto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAutoActionPerformed(evt);
            }
        });
        panelConsola.add(botonAuto);
        panelConsola.add(filler1);

        botonPaso.setText("paso");
        botonPaso.setAlignmentX(0.5F);
        botonPaso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPasoActionPerformed(evt);
            }
        });
        panelConsola.add(botonPaso);
        panelConsola.add(filler3);

        botonIniciar.setText("iniciar");
        botonIniciar.setAlignmentX(0.5F);
        botonIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonIniciarActionPerformed(evt);
            }
        });
        panelConsola.add(botonIniciar);
        panelConsola.add(filler4);

        etiquetaTiempo.setText("00:00");
        etiquetaTiempo.setAlignmentX(0.5F);
        panelConsola.add(etiquetaTiempo);
        panelConsola.add(filler5);

        getContentPane().add(panelConsola, java.awt.BorderLayout.EAST);

        panelBorde.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        panelBorde.setLayout(new java.awt.BorderLayout());

        panelJuego.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelJuego.setPreferredSize(new java.awt.Dimension(500, 500));
        panelJuego.setLayout(new java.awt.BorderLayout());
        panelBorde.add(panelJuego, java.awt.BorderLayout.CENTER);

        getContentPane().add(panelBorde, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonPasoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPasoActionPerformed
        mundo.mover();
        lienzo.validate();
        lienzo.repaint();
}//GEN-LAST:event_botonPasoActionPerformed

    private void botonAutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAutoActionPerformed
        actualizarEstado();
    }//GEN-LAST:event_botonAutoActionPerformed

    private void botonIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonIniciarActionPerformed
        iniciar();
//        botonAuto.setSelected(true);
        actualizarEstado();
    }//GEN-LAST:event_botonIniciarActionPerformed

    private void comboPruebaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboPruebaActionPerformed
        iniciar();
    }//GEN-LAST:event_comboPruebaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (Exception e) {
            // handle exception
        }
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Marco().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton botonAuto;
    private javax.swing.JButton botonIniciar;
    private javax.swing.JButton botonPaso;
    private javax.swing.JComboBox comboPrueba;
    private javax.swing.JLabel etiquetaTiempo;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.Box.Filler filler5;
    private javax.swing.JPanel panelBorde;
    private javax.swing.JPanel panelConsola;
    private javax.swing.JPanel panelJuego;
    // End of variables declaration//GEN-END:variables
}
